[package]
name = "day11"
version = "0.1.0"
authors = ["Huáng Jùnliàng <jlhwung@gmail.com>"]
edition = "2018"

[lib]
name = "day11"
path = "src/lib.rs"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
